### ISSUE TITLE
sample_state_to_leaf

### ISSUE THREAD

**Issue by yffbit** [facebookresearch/rebel#10]
https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L210-L212
![image](https://user-images.githubusercontent.com/38515904/102640901-29f8c080-4196-11eb-9dd6-8ca810b11e03.png)

The code for `sample_state_to_leaf` is a little different from the description in the paper. You sample a hand at every decision point in the path down to leaf for  activate player. In the paper,  it only samples a hand at the root PBS for both player.

**Comment by akhti** [comment]
Indeed. It shouldn't make a difference as `sampling_beliefs` include `reach` probability information, i.e., we sample from a more restricted subset as we go down the tree. Sampling at the beginning of the subtree is just cleaner.

**Comment by yffbit** [comment]
@akhti 
At test time, given the initial uniform belief, the process of the algorithm:
1. Build depth-limited subgame for current PBS;
2. Solve the subgame with T iterations. At a random iteration, store the strategy profile;
3. Use the average strategy to act against opponent until reaching leaf node. Store the real path;
4. Use the stored profile and path to compute the PBS for the leaf node, then repeat 1~4 until the game ends.
Am I right?

**Comment by akhti** [comment]
Oh, that's the most interesting part!

Test time could be "play" time or exploitability computation time.
For the former we run [compute_sampled_strategy_recursive_to_leaf](https://github.com/facebookresearch/rebel/blob/master/csrc/liars_dice/recursive_solving.cc#L301) function. The trick is: because we sample iteration, we use the last iteration strategy as we prove this is sound. Here's the algo:

1. Build depth-limited subgame for current PBS;
2. Sample an iteration from [1, T]. We use [non-uniform sampling](https://github.com/facebookresearch/rebel/blob/master/csrc/liars_dice/recursive_solving.cc#L306-L309) to match [linear-CFR weighting
](https://github.com/facebookresearch/rebel/blob/master/csrc/liars_dice/subgame_solving.cc#L581-L589).
3. [Solve](https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L76) the subgame and take the **last** strategy
4. Use this strategy to play until a leaf is reached. Once a leaf is reached, use beliefs in the node (still from the last strategy) and repeat.

Note, that in the code for Liar's dice we compute the policy for the whole tree at once, because our main metric is exportability rather than head2head.

The "real" strategy for the whole tree is a mixure of the exponential number of strategies described above. We only approximate this by summing some number of samples (~1000) in [ParallerSampledStrategyComputor ](https://github.com/facebookresearch/rebel/blob/master/csrc/liars_dice/recursive_eval.cc#L117). 


Hope this helps!

**Comment by yffbit** [comment]
I know the purpose of function `compute_strategy_recursive_to_leaf`. It recursively solve subgame and traverse the subgame nodes using [BFS method](https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L90) and copy the [action distribution](https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L108) at each node in the subgame into its corresponding node in the full game. When reaching the non-terminal leaf node, it [recursively call itself](https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L129) so that it can traverse all the nodes in full game and get the full game strategy profile. After we get the full game strategy profile, we can evaluate the profile with [exploitability](https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/subgame_solving.cc#L818). We can run `compute_strategy_recursive_to_leaf` many times to get the [exponential number of full game strategy profiles](https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_eval.cc#L344-L347). Every time you get a  full game strategy profile, you can compute the average full game strategy profile using [activate player reaching probability weighting](https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_eval.cc#L349-L363). You can also compute the exploitability of average full game strategy profile to get the exploitability-time curve.



What I mean about `test time` is playing against human/agent in real time. Do you mean that we can get the exponential number of full game strategy profiles offline and use the final average full game strategy profile to play against human online?
The process I mentioned above
> At test time, given the initial uniform belief, the process of the algorithm:
> 
> 1. Build depth-limited subgame for current PBS;
> 2. Solve the subgame with T iterations. At a random iteration, store the strategy profile;
> 3. Use the average strategy to act against opponent until reaching leaf node. Store the real path;
> 4. Use the stored profile and path to compute the PBS for the leaf node, then repeat 1~4 until the game ends.
> 
doesn't traverse the full game but only a real path down to terminal node, just like the process for training. In that case, we need not to store the full game strategy profile. Only the subgame strategy is needed. When the full game is extremely huge, it can save a lot of memory.

**Comment by akhti** [comment]
> The process I mentioned above doesn't traverse the full game but only a real path down to terminal node, just like the process for training.

Yes, this algorithm is correct except for using the last policy at random iteration instead of the average one.

**Comment by yffbit** [comment]
When playing against human/agent, we sample an iteration from [1, T] and solve the subgame for this number of iterations,
https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L311-L324
https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L85-L86
 use `partial_strategy` to play against human/agent, 
https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L97-L99
https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L108
 use `partial_belief_strategy` to compute the new PBS at the reached leaf node,
https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L100-L102
https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L119-L120
https://github.com/facebookresearch/rebel/blob/6e9f6f510d94320ca75b4383d848f1e05c4b8066/csrc/liars_dice/recursive_solving.cc#L127-L128
just like the process in function `compute_strategy_recursive_to_leaf` but not really need to traverse the full game to get the full game strategy profile which is for computing the exploitability metric.
Do you mean this?

**Comment by akhti** [comment]
Yes, exactly!
