### ISSUE TITLE
something about test

### ISSUE THREAD

**Issue by zhaoyin214** [facebookresearch/rebel#26]
When playing with a human player, how do we guess the opponent's hand distribution?

Of course, at the root of the game, we can initialize it as a uniform distribution. After that, as the game going action by action, do we need to maintain a path to tracking the history actions and beliefs? For example, assuming the robot is the dealer, at game start, the robot need to do an action at first. We need to build a depth limited subgame tree and search on it to find out the strategy at root according the robot's hand. An action can be sampled according the strategy, say "call", then, the human player do an action, say "raise a half pot", how do we update the human's hand distribution? Do we need to build a sub tree rooted at **the robot last action** and search as the robot does and then update the human beliefs to those at child node of "raise a half pot"? If the human player's action if out of the predefined actions in training, how do we build the sub tree?

**Comment by akhti** [comment]
We do not model chance nodes = robot. We assume that chance nodes creates either private observations (info sets) or public observations. Instead of tracking the history, we maintain beliefs over private observations. A pair (belief, public state) constitutes a Public Belief State (PBS). Knowing PBS is enough to define the Nash value and the optimal play.

To update the beliefs over the opponent's hand after an action is taken, we use the opponent's policy. We do not know the actual optimal policy, so instead we use one from CFR assuming the values are defined from the value function in leaf PBSs. 

Whenever we happen to meet a chance node that creates public observations, e.g., flop, we just update the public state part of PBS without touching beliefs. Note, that value of pre-flop PBS is a function of  post-flop PBS values, as we can take a mean over possible flops given possible distribution of hands the players have
